#### Numpy:Package For Multidimensional array

In [1]:
import numpy as np

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
list_of_lists=[[1,2,3,],[4,5,6],[7,8,9]]
np.array(list_of_lists)
            

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,65)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64])

In [8]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [15]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(2,4)

array([[0.58503855, 0.33950953, 0.51407743, 0.82206458],
       [0.08840574, 0.20346269, 0.62510532, 0.13312271]])

In [17]:
arr=np.random.randn(2,4)
arr

array([[ 0.38033594, -1.33793171, -1.33306718,  1.45757579],
       [-0.06583454,  0.07006398,  0.75963814,  0.04585499]])

In [18]:
np.random.randint(2,10)

9

In [21]:
np.random.randint(20,56,100)

array([36, 49, 22, 35, 30, 28, 47, 33, 55, 34, 55, 43, 43, 36, 40, 53, 36,
       41, 43, 42, 45, 46, 21, 21, 27, 27, 20, 28, 25, 55, 53, 41, 52, 33,
       45, 51, 22, 49, 46, 49, 41, 26, 45, 40, 22, 49, 48, 40, 30, 47, 27,
       50, 34, 25, 34, 37, 36, 28, 28, 33, 35, 30, 49, 20, 29, 24, 41, 45,
       28, 22, 39, 30, 47, 43, 24, 25, 39, 28, 46, 28, 24, 45, 44, 51, 30,
       50, 24, 45, 29, 34, 53, 24, 26, 40, 36, 47, 45, 29, 53, 50])

In [22]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
rand_array=np.random.randint(0,100,20)
rand_array

array([43, 63, 27, 18, 71, 31, 69, 39,  8, 35, 31, 88, 89, 55, 39, 22, 43,
       76, 93, 50])

In [25]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [32]:
sample_array.reshape(5,9)

ValueError: cannot reshape array of size 30 into shape (5,9)

In [33]:
rand_array.min()

8

In [34]:
rand_array.max()

93

In [35]:
rand_array.argmax()

18

In [36]:
a=np.eya(5)
a

AttributeError: module 'numpy' has no attribute 'eya'

In [37]:
a.T

NameError: name 'a' is not defined

In [38]:
sample_array=np.arange(10.21)
sample_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
sample_array[0:7]

array([0., 1., 2., 3., 4., 5., 6.])

In [40]:
subset_sample_array=sample_array[0,7]
subset_sample_array


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [41]:
subset_sample_array[:]=1001
subset_sample_array

NameError: name 'subset_sample_array' is not defined

#### Two-Dimensional array

In [42]:
import numpy as np

In [43]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [44]:
sample_matrix[0][2]

1

In [45]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [46]:
sample_matrix[2]

array([56, 76, 24,  7])

In [47]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

#### Selection techniques

In [49]:
sample_array=np.arange(1,20)

In [50]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [51]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [54]:
np.exp(sample_array)#exponetial

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [53]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [55]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [56]:
np.max(sample_array)

19

In [57]:
np.min(sample_array)

1

In [58]:
np.argmax(sample_array)

18

In [59]:
np.argmin(sample_array)

0

In [61]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [62]:
np.std(sample_array)

5.477225575051661

In [63]:
np.var(sample_array)

30.0

In [64]:
np.mean(sample_array)

10.0

In [65]:
array=np.random.randn(3,4)
array

array([[-1.40520977,  1.44737033,  0.77974835, -0.84871565],
       [ 0.4985864 , -0.21243676,  0.43229966,  0.93754998],
       [ 0.67767122,  1.10513689,  0.75222056, -1.08817777]])

In [66]:
np.round(array,decimals=2)

array([[-1.41,  1.45,  0.78, -0.85],
       [ 0.5 , -0.21,  0.43,  0.94],
       [ 0.68,  1.11,  0.75, -1.09]])

In [67]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

#### pandas


In [68]:
import pandas as pd
import numpy as pd

In [ ]:
labels=['w','x','y','z']
 